"""
generate_input.py  —  Input file generator for CS5205 Assignment 5

Generates scheduling input files in the exact format expected by assg05.py.

Modes:
  --mode sat       Generate a SAT-guaranteed instance (valid schedule exists)
  --mode unsat     Generate an UNSAT-guaranteed instance (no valid schedule)
  --mode random    Generate a purely random instance (outcome unknown)
  --mode batch     Generate multiple files at once (mix of SAT + UNSAT)

Usage examples:
  python3 generate_input.py                          # one SAT instance → input.txt
  python3 generate_input.py --mode unsat             # one UNSAT instance
  python3 generate_input.py --mode random            # one random instance
  python3 generate_input.py --mode sat --rooms 4 --courses 6 --days 25
  python3 generate_input.py --mode batch --count 10  # 10 files in ./inputs/
  python3 generate_input.py --seed 42                # reproducible output
  python3 generate_input.py --output my_test.txt     # custom output filename
  python3 generate_input.py --preview                # print file to screen too
"""

import os
import random
import argparse


# ─────────────────────────────────────────────────────────────────────────────
# Helper: write one instance in assignment format
# ─────────────────────────────────────────────────────────────────────────────

def write_instance(filepath, M, courses, label=""):
    """
    Write a scheduling instance to `filepath` in the assignment format:

        M <rooms>
        N <courses>
        C <id> <start> <deadline> <duration>
        ...
    """
    os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)
    with open(filepath, "w") as f:
        if label:
            f.write(f"% Instance type : {label}\n")
        f.write(f"% Generated by generate_input.py\n")
        f.write(f"%\n")
        f.write(f"% number of rooms\n")
        f.write(f"M {M}\n")
        f.write(f"% number of short-term courses\n")
        f.write(f"N {len(courses)}\n")
        f.write(f"% course-id  start-day  deadline  duration\n")
        for c in courses:
            f.write(f"C {c['id']:>3}  {c['start']:>4}  {c['deadline']:>4}  {c['duration']:>4}\n")
    return filepath


def course(cid, start, deadline, duration):
    """Simple dict for a course (avoids importing assg05)."""
    return {"id": cid, "start": start, "deadline": deadline, "duration": duration}


def preview(filepath):
    """Print file contents to stdout."""
    print(f"\n{'─'*50}")
    print(f"  File: {filepath}")
    print('─'*50)
    with open(filepath) as f:
        print(f.read())
    print('─'*50)


# ─────────────────────────────────────────────────────────────────────────────
# Generator 1 — SAT instance (valid schedule built first)
#
# How it works:
#   1. Decide M rooms and N courses.
#   2. For each room, place courses one after another on consecutive days
#      (greedy bin-pack). This gives us the ACTUAL start day for each course.
#   3. From the actual start day, create a window:
#        start    = actual_start - random_slack_before
#        deadline = actual_end   + random_slack_after
#      The actual start day always lies within [start, deadline - dur + 1],
#      so a valid schedule always exists → SAT guaranteed.
# ─────────────────────────────────────────────────────────────────────────────

def gen_sat(rng, M, max_courses, max_days, max_duration, max_slack=3):
    """Return (M, courses_list) guaranteed to be SAT."""
    courses = []
    cid = 1
    target_N = rng.randint(max(2, max_courses // 2), max_courses)

    for j in range(M):
        day = 1
        while cid <= target_N and day <= max_days:
            duration = rng.randint(1, max_duration)
            if day + duration - 1 > max_days:
                break  # room full
            actual_start = day
            actual_end   = day + duration - 1

            # Random slack around the actual placement
            slack_before = rng.randint(0, min(max_slack, actual_start - 1))
            slack_after  = rng.randint(0, min(max_slack, max_days - actual_end))

            s_i = actual_start - slack_before
            d_i = actual_end   + slack_after

            courses.append(course(cid, s_i, d_i, duration))
            day += duration + rng.randint(0, 2)   # optional gap
            cid += 1
        if cid > target_N:
            break

    return M, courses


# ─────────────────────────────────────────────────────────────────────────────
# Generator 2 — UNSAT instance
#
# Two strategies:
#
#  "tight"    → Give course #1 a window narrower than its own duration.
#               deadline - start + 1  <  duration
#               → No valid start day → UNSAT immediately.
#
#  "overload" → Use only 1 room and a narrow window (e.g. 8 days).
#               Pack in courses whose total duration > window size.
#               A conflict is mathematically unavoidable → UNSAT.
# ─────────────────────────────────────────────────────────────────────────────

def gen_unsat(rng, M, max_courses, max_days, strategy="tight"):
    """Return (M, courses_list) guaranteed to be UNSAT."""
    courses = []

    if strategy == "tight":
        # ── Strategy A: impossible window ────────────────────────────────
        N = rng.randint(3, max_courses)
        for cid in range(1, N + 1):
            if cid == 1:
                # Make this course impossible: window too narrow
                duration = rng.randint(4, 7)
                start    = rng.randint(1, max_days // 2)
                deadline = start + duration - 2       # ← one day short!
            else:
                duration = rng.randint(1, 4)
                start    = rng.randint(1, max_days - duration)
                deadline = rng.randint(start + duration - 1, max_days)
            courses.append(course(cid, start, deadline, duration))

    else:  # strategy == "overload"
        # ── Strategy B: more work than room capacity ──────────────────────
        M = 1                                    # force single room
        window_size = rng.randint(5, 10)         # e.g. 8 available days
        win_start   = 1
        win_end     = win_start + window_size - 1

        N = rng.randint(3, max_courses)
        total_dur = 0
        for cid in range(1, N + 1):
            duration   = rng.randint(2, 4)
            total_dur += duration
            courses.append(course(cid, win_start, win_end, duration))

        # Guarantee overflow: if it somehow fits, add one more course
        if total_dur <= window_size:
            extra = window_size - total_dur + 1
            courses.append(course(N + 1, win_start, win_end, extra))

    return M, courses


# ─────────────────────────────────────────────────────────────────────────────
# Generator 3 — purely random instance (outcome unknown)
# ─────────────────────────────────────────────────────────────────────────────

def gen_random(rng, M, max_courses, max_days, max_duration):
    """Return (M, courses_list) with random parameters (SAT or UNSAT)."""
    N = rng.randint(2, max_courses)
    courses = []
    for cid in range(1, N + 1):
        duration = rng.randint(1, max_duration)
        start    = rng.randint(1, max(1, max_days - duration))
        deadline = rng.randint(start + duration - 1, max_days)
        courses.append(course(cid, start, deadline, duration))
    return M, courses


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Input file generator for CS5205 Assg-5 SAT scheduling",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument("--mode",     choices=["sat", "unsat", "random", "batch"],
                        default="sat",
                        help="Generation mode (default: sat)")
    parser.add_argument("--strategy", choices=["tight", "overload"],
                        default=None,
                        help="UNSAT strategy: 'tight' (bad window) or "
                             "'overload' (too many courses). "
                             "Default: alternates in batch mode, 'tight' otherwise.")
    parser.add_argument("--rooms",    type=int, default=None,
                        help="Number of rooms M (default: random 2-5)")
    parser.add_argument("--courses",  type=int, default=None,
                        help="Max number of courses N (default: random 3-8)")
    parser.add_argument("--days",     type=int, default=30,
                        help="Total days in the horizon (default: 30)")
    parser.add_argument("--duration", type=int, default=5,
                        help="Max course duration (default: 5)")
    parser.add_argument("--count",    type=int, default=10,
                        help="Number of files to generate in batch mode (default: 10)")
    parser.add_argument("--seed",     type=int, default=None,
                        help="Random seed for reproducibility")
    parser.add_argument("--output",   type=str, default="input.txt",
                        help="Output filename for single-file modes (default: input.txt)")
    parser.add_argument("--outdir",   type=str, default="inputs",
                        help="Output directory for batch mode (default: ./inputs/)")
    parser.add_argument("--preview",  action="store_true",
                        help="Print generated file(s) to stdout")
    args = parser.parse_args()

    rng = random.Random(args.seed)
    M           = args.rooms    or rng.randint(2, 5)
    max_courses = args.courses  or 8
    max_days    = args.days
    max_dur     = args.duration

    # ── Single-file modes ──────────────────────────────────────────────────
    if args.mode == "sat":
        M_out, courses = gen_sat(rng, M, max_courses, max_days, max_dur)
        label = "SAT (by construction)"
        write_instance(args.output, M_out, courses, label)
        print(f"[SAT]    {args.output}  →  M={M_out}, N={len(courses)}")
        if args.preview:
            preview(args.output)

    elif args.mode == "unsat":
        strategy = args.strategy or "tight"
        M_out, courses = gen_unsat(rng, M, max_courses, max_days, strategy)
        label = f"UNSAT (strategy={strategy})"
        write_instance(args.output, M_out, courses, label)
        print(f"[UNSAT]  {args.output}  →  M={M_out}, N={len(courses)}  strategy={strategy}")
        if args.preview:
            preview(args.output)

    elif args.mode == "random":
        M_out, courses = gen_random(rng, M, max_courses, max_days, max_dur)
        label = "RANDOM (outcome unknown)"
        write_instance(args.output, M_out, courses, label)
        print(f"[RAND]   {args.output}  →  M={M_out}, N={len(courses)}")
        if args.preview:
            preview(args.output)

    # ── Batch mode ─────────────────────────────────────────────────────────
    elif args.mode == "batch":
        count     = args.count
        half      = count // 2
        remainder = count - half          # handles odd counts (extra goes to UNSAT)

        print(f"\nGenerating {count} files into '{args.outdir}/'")
        print(f"  {half} SAT  +  {remainder} UNSAT\n")

        generated = []

        # SAT files
        for k in range(half):
            M_k = rng.randint(2, 5) if args.rooms is None else args.rooms
            M_out, courses = gen_sat(rng, M_k, max_courses, max_days, max_dur)
            fname = os.path.join(args.outdir, f"sat_{k+1:03d}.txt")
            write_instance(fname, M_out, courses, "SAT (by construction)")
            generated.append(("SAT", fname, M_out, len(courses)))
            print(f"  [SAT   {k+1:>3}]  {fname}  M={M_out}  N={len(courses)}")
            if args.preview:
                preview(fname)

        # UNSAT files — alternate between 'tight' and 'overload'
        for k in range(remainder):
            strategy = "tight" if args.strategy is None else args.strategy
            if args.strategy is None:
                strategy = "tight" if k % 2 == 0 else "overload"
            M_k = rng.randint(1, 3) if args.rooms is None else args.rooms
            M_out, courses = gen_unsat(rng, M_k, max_courses, max_days, strategy)
            fname = os.path.join(args.outdir, f"unsat_{k+1:03d}.txt")
            write_instance(fname, M_out, courses, f"UNSAT (strategy={strategy})")
            generated.append(("UNSAT", fname, M_out, len(courses)))
            print(f"  [UNSAT {k+1:>3}]  {fname}  M={M_out}  N={len(courses)}  strategy={strategy}")
            if args.preview:
                preview(fname)

        print(f"\n✓ Done. {len(generated)} files written to '{args.outdir}/'")
        print(f"\nTo solve all files with assg05.py:")
        print(f"  for f in {args.outdir}/*.txt; do python3 assg05.py --input $f; done")


if __name__ == "__main__":
    main()